class Produto:
    def __init__(self, 
                 id: str = None,
                 codigo: int = None,
                 designacao: str = None,
                 descricao: str = None,
                 produto_servico: str = None,
                 vendivel: str = None,
                 compravel: str = None,
                 condigo_barra: int = None,
                 preco_custo: float = None,
                 preco_venda: float = None,
                 pr_categoria_id: str = None,
                 entidade_id: str = None,
                 glb_user_id: str = None,
                 pr_iva_id: str = None,
                 pr_iva_compra_id: str = None,
                 pr_unidade_id: str = None,
                 rfid: int = None,
                 pos: str = None,
                 dt_registro = None,
                 dt_alteracao = None,
                 estado: str = None,
                 desconto_comercial: float = None,
                 foto_perfil: str = None) -> None:
        
            self.__id = id
            self.__codigo = codigo
            self.__designacao = designacao
            self.__descricao = descricao
            self.__produto_servico = produto_servico
            self.__vendivel = vendivel
            self.__compravel = compravel
            self.__codigo_barra = condigo_barra
            self.__preco_custo = preco_custo
            self.__preco_venda = preco_venda
            self.__pr_categoria_id = pr_categoria_id
            self.__entidade_id = entidade_id
            self.__glb_user_id = glb_user_id
            self.__pr_iva_id = pr_iva_id
            self.__pr_iva_compra_id = pr_iva_compra_id
            self.__pr_unidade_id = pr_unidade_id
            self.__rfid = rfid
            self.__pos = pos
            self.__dt_registro = dt_registro
            self.__dt_alteracao = dt_alteracao
            self.__estado = estado
            self.__desconto_comercial = desconto_comercial
            self.__foto_perfil = foto_perfil